### ISSUE TITLE
Update and migrate the java app to Spring Boot lastest version

### ISSUE THREAD

**Issue by craicic** [craicic/game-library-service#10]
Lastest version is 3.1.1
2.7 to 3 guide : [https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)
A short guide to [migrate Hibernate to 6](https://thorben-janssen.com/things-to-know-when-migrating-to-hibernate-6-x)
Associated branch is feature-spring-update

**Comment by vishalsingh2972** [comment]
@craicic can you assign this to me would like to work on this!

**Comment by craicic** [comment]
Done ! If you need : questions and suggestions welcome
